app = "synergo"
primary_region = "otp"

[build]
compose = "docker-compose.yml"
# ────────────────────────────────

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[env]
  DB_HOST=tramway.proxy.rlwy.net
  DB_PORT=23723
  DB_USERNAME=postgres
  DB_PASSWORD=lkWPBdkBLhJfMCgSSGAEumIoJkmSVSlM
  DB_NAME=railway
  
  JWT_SECRET=synergo-secret
  
  REDIS_HOST=redis
  REDIS_PORT=6379
